
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rhoas.redhat.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - rhoas.redhat.com
  resources:
  - managedkafkaconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhoas.redhat.com
  resources:
  - managedkafkaconnections/status
  verbs:
  - get
  - patch
  - update
