apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: rhoas-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ManagedKafkaConnection schema
      displayName: Managed Kafka Connection
      kind: ManagedKafkaConnection
      name: managedkafkaconnections.oas.redhat.com
      version: v1
  description: Managed Services Operator
  displayName: Managed Services Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kafka
  - services
  links:
  - name: Rhoas Operator
    url: https://rhoas-operator.domain
  maintainers:
  - email: wtrocki@redhat.com
    name: Wojciech
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
