# The following patch adds a directive for certmanager to inject CA into the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    service.binding/host: 'path={.spec.bootstrapServer.host}'
    service.binding/credentials: 'path={.spec.credentials.secretName},objectType=Secret'
  name: managedkafkaconnections.rhoas.redhat.com
